// example 5: fetch data on the server side (in getServerSideProps)
// getServerSideProps will be called everytime page is requested/load

import Head from 'next/head';
import { getProducts } from '../lib/products';
import Style from '../styles/Home.module.css';

// create special next.js function called "getServerSideProps" that is executed on the server side
export async function getServerSideProps() {
  console.log('[HomePage] getServerSideProps()');
  const products = await getProducts();
  return { props: { products } };
}

const Home = ({ products }: any) => {
  console.log('[HomePage] render: ', products);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={Style.main}>
        <ul>
          {products.map((product: any) => (
            <li key={product.id}>{product.title}</li>
          ))}
        </ul>
      </main>
    </div>
  );
};

export default Home;
