// example 3a : fetch data on the client side (in useEffect)
// fetch data when the component is mounted as do in a plain React App (will re-request data everytime we load page)
// directly from an external API

import Head from 'next/head';
import { useState, useEffect } from 'react';
import { getProducts } from '../lib/products';
import Style from '../styles/Home.module.css';

const Home = () => {
  const [products, setProducts] = useState<any[]>([]);
  useEffect(() => {
    // using promise "then" and pass setProducts to update the state variable
    getProducts().then(setProducts);
  }, []);
  console.log('[HomePage] render: ', products);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={Style.main}>
        <ul>
          {products.map((product) => (
            <li key={product.id}>{product.title}</li>
          ))}
        </ul>
      </main>
    </div>
  );
};

export default Home;
