// example 3b : fetch data on the client side (in useEffect)
// fetch data when the component is mounted as do in a plain React App (will re-request data everytime we load page)
// from an internal API route

import Head from 'next/head';
import { useState, useEffect } from 'react';
import Style from '../styles/Home.module.css';

function Home() {
  const [products, setProducts] = useState<any[]>([]);
  useEffect(() => {
    async function fetchMyAPI() {
      const response = await fetch('api/products');
      const products = await response.json();
      setProducts(products);
    }

    fetchMyAPI();
  }, []);
  console.log('[HomePage] render: ', products);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={Style.main}>
        <ul>
          {products.map((product) => (
            <li key={product.id}>{product.title}</li>
          ))}
        </ul>
      </main>
    </div>
  );
}

export default Home;
