// example 2: fetch data on the server side (in getStaticProps)
// when components is pre-rendered to HTML on the server it already includes the real product data (statically generated at build time)

import Head from 'next/head';
import { getProducts } from '../lib/products';
import Style from '../styles/Home.module.css';

// create special next.js function called "getStaticProps" that is executed on the server side
export async function getStaticProps() {
  console.log('[HomePage] getStaticProps()');
  const products = await getProducts();
  return { props: { products } };
}

const Home = ({ products }: any) => {
  console.log('[HomePage] render: ', products);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={Style.main}>
        <ul>
          {products.map((product: any) => (
            <li key={product.id}>{product.title}</li>
          ))}
        </ul>
      </main>
    </div>
  );
};

export default Home;
